In [1]:
#Importing libraries
import pandas as pd
import numpy as np

In [2]:
#Loading a CSV file
df = pd.read_csv('fifa21 raw data v2.csv', low_memory=False)
df

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,\n\n\n\nWuhan Zall,...,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,\n\n\n\nOldham Athletic,...,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,\n\n\n\nDerry City,...,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

In [3]:
#Number of rows and columns
df.shape

(18979, 77)

In [4]:
#Column names
df.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [5]:
#Renaming column '↓OVA' to 'OVA'
df.rename(columns={'↓OVA':'OVA'}, inplace=True)

In [6]:
#Showing result
df.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       'OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [7]:
#Any duplicate rows in df?
df.duplicated().sum()

0

In [8]:
#Finding columns with null values
df.columns[df.isnull().any()]

Index(['Loan Date End', 'Hits'], dtype='object')

In [9]:
#Finding unique values in 'Loan Date End'
df['Loan Date End'].unique()

array([nan, 'Jun 30, 2021', 'Dec 31, 2020', 'Jan 30, 2021',
       'Jun 30, 2022', 'May 31, 2021', 'Jul 5, 2021', 'Dec 31, 2021',
       'Jul 1, 2021', 'Jan 1, 2021', 'Aug 31, 2021', 'Jan 31, 2021',
       'Dec 30, 2021', 'Jun 23, 2021', 'Jan 3, 2021', 'Nov 27, 2021',
       'Jan 17, 2021', 'Jun 30, 2023', 'Jul 31, 2021', 'Nov 22, 2020',
       'May 31, 2022', 'Dec 30, 2020', 'Jan 4, 2021', 'Nov 30, 2020',
       'Aug 1, 2021'], dtype=object)

In [10]:
#Casting to type string, to replace nan with 'Not a loan'
df['Loan Date End'] = df['Loan Date End'].astype(str)
df['Loan Date End'] = df['Loan Date End'].replace('nan', 'Not a loan')

In [11]:
#Checking if correct
df['Loan Date End'].unique()

array(['Not a loan', 'Jun 30, 2021', 'Dec 31, 2020', 'Jan 30, 2021',
       'Jun 30, 2022', 'May 31, 2021', 'Jul 5, 2021', 'Dec 31, 2021',
       'Jul 1, 2021', 'Jan 1, 2021', 'Aug 31, 2021', 'Jan 31, 2021',
       'Dec 30, 2021', 'Jun 23, 2021', 'Jan 3, 2021', 'Nov 27, 2021',
       'Jan 17, 2021', 'Jun 30, 2023', 'Jul 31, 2021', 'Nov 22, 2020',
       'May 31, 2022', 'Dec 30, 2020', 'Jan 4, 2021', 'Nov 30, 2020',
       'Aug 1, 2021'], dtype=object)

In [12]:
#Finding unique values in 'Hits'
df['Hits'].unique()

array(['771', '562', '150', '207', '595', '248', '246', '120', '1.6K',
       '130', '321', '189', '175', '96', '118', '216', '212', '154',
       '205', '202', '339', '408', '103', '332', '86', '173', '161',
       '396', '1.1K', '433', '242', '206', '177', '1.5K', '198', '459',
       '117', '119', '209', '84', '187', '165', '203', '65', '336', '126',
       '313', '124', '145', '538', '182', '101', '45', '377', '99', '194',
       '403', '414', '593', '374', '245', '3.2K', '266', '299', '309',
       '215', '265', '211', '112', '337', '70', '159', '688', '116', '63',
       '144', '123', '71', '224', '113', '168', '61', '89', '137', '278',
       '75', '148', '176', '197', '264', '214', '247', '402', '440',
       '1.7K', '2.3K', '171', '320', '657', '87', '259', '200', '255',
       '253', '196', '60', '97', '85', '169', '256', '132', '239', '166',
       '121', '109', '32', '46', '122', '48', '527', '199', '282', '51',
       '1.9K', '642', '155', '323', '288', '497', '509', '79', '49',
       '270', '511', '80', '128', '115', '156', '204', '143', '140',
       '152', '220', '134', '225', '94', '74', '135', '142', '50', '77',
       '40', '107', '193', '179', '34', '64', '453', '57', '81', '28',
       '78', '133', '43', '425', '88', '42', '36', '233', '376', '210',
       '444', '100', '263', '98', '29', '160', '39', '257', '6', '310',
       '138', '62', '293', '285', '362', '66', '69', '58', '21', '20',
       '131', '38', '406', '68', '108', '110', '93', '512', '443', '306',
       '352', '422', '585', '346', '178', '841', '76', '394', '72', '172',
       '44', '407', '230', '367', '295', '157', '243', '56', '111', '326',
       '679', '18', '92', '59', '25', '184', '53', '12', '90', '55', '73',
       '11', '566', '180', '83', '262', '17', '26', '31', '280', '359',
       '213', '297', '387', '480', '381', '677', '486', '8', '244', '129',
       '388', '275', '319', '2K', '52', '91', '421', '153', '27', '41',
       '222', '35', '102', '23', '30', '33', '146', '13', '19', '14',
       '106', '276', '568', '353', '47', '478', '249', '254', '369',
       '219', '565', '237', '227', '434', '375', '162', '605', '654', '3',
       '7', '9', '104', '114', '186', '446', '756', '22', '139', '500',
       '67', '147', '149', '16', '82', '54', '37', '15', '1.3K', '3K',
       '952', '5', '749', '541', '330', '393', '517', '770', '409', '170',
       '125', '283', '342', '363', '580', '105', '217', '24', '141', '10',
       '427', '158', '426', '4', '666', '181', '324', '979', '1.4K',
       '302', '751', '298', '411', '944', '2', '947', '292', '349', '621',
       '1', '2.8K', '338', '287', '261', '218', '1.8K', '240', '279',
       '229', '188', '315', '664', '613', '190', '706', '127', '462',
       '386', '695', '491', '167', '281', '250', '307', '95', '231',
       '174', '680', '633', '221', '348', '602', '183', '653', '195',
       '164', '151', '258', '8.4K', '343', '419', '655', '136', '399',
       '531', '357', '228', '385', '312', '340', '238', '487', '355',
       '499', '4.3K', '296', '515', '943', '1.2K', '903', '335', '191',
       '594', '267', '617', '516', '504', '331', '652', '410', '550',
       '473', '442', '344', '208', '1K', '2.5K', '273', '485', '826',
       '192', '405', '941', '477', '644', '303', '417', '6K', nan],
      dtype=object)

In [13]:
#Replacing nan value with 0, expected that if there was not a value, it means that is was 0 Hits
df['Hits'].fillna(value=0, inplace=True)

In [14]:
#Converitng short format (2.5K) to long format (2500), in the end casting as int whole column
def convert_k_to_thousands(value):
    if isinstance(value, str) and 'K' in value:
        return float(value.replace('K', '')) * 1000
    return value
    
df['Hits'] = df['Hits'].apply(convert_k_to_thousands)
df['Hits'] = df['Hits'].astype(int)

In [15]:
#Checking results
df['Hits'].unique()

array([ 771,  562,  150,  207,  595,  248,  246,  120, 1600,  130,  321,
        189,  175,   96,  118,  216,  212,  154,  205,  202,  339,  408,
        103,  332,   86,  173,  161,  396, 1100,  433,  242,  206,  177,
       1500,  198,  459,  117,  119,  209,   84,  187,  165,  203,   65,
        336,  126,  313,  124,  145,  538,  182,  101,   45,  377,   99,
        194,  403,  414,  593,  374,  245, 3200,  266,  299,  309,  215,
        265,  211,  112,  337,   70,  159,  688,  116,   63,  144,  123,
         71,  224,  113,  168,   61,   89,  137,  278,   75,  148,  176,
        197,  264,  214,  247,  402,  440, 1700, 2300,  171,  320,  657,
         87,  259,  200,  255,  253,  196,   60,   97,   85,  169,  256,
        132,  239,  166,  121,  109,   32,   46,  122,   48,  527,  199,
        282,   51, 1900,  642,  155,  323,  288,  497,  509,   79,   49,
        270,  511,   80,  128,  115,  156,  204,  143,  140,  152,  220,
        134,  225,   94,   74,  135,  142,   50,   77,   40,  107,  193,
        179,   34,   64,  453,   57,   81,   28,   78,  133,   43,  425,
         88,   42,   36,  233,  376,  210,  444,  100,  263,   98,   29,
        160,   39,  257,    6,  310,  138,   62,  293,  285,  362,   66,
         69,   58,   21,   20,  131,   38,  406,   68,  108,  110,   93,
        512,  443,  306,  352,  422,  585,  346,  178,  841,   76,  394,
         72,  172,   44,  407,  230,  367,  295,  157,  243,   56,  111,
        326,  679,   18,   92,   59,   25,  184,   53,   12,   90,   55,
         73,   11,  566,  180,   83,  262,   17,   26,   31,  280,  359,
        213,  297,  387,  480,  381,  677,  486,    8,  244,  129,  388,
        275,  319, 2000,   52,   91,  421,  153,   27,   41,  222,   35,
        102,   23,   30,   33,  146,   13,   19,   14,  106,  276,  568,
        353,   47,  478,  249,  254,  369,  219,  565,  237,  227,  434,
        375,  162,  605,  654,    3,    7,    9,  104,  114,  186,  446,
        756,   22,  139,  500,   67,  147,  149,   16,   82,   54,   37,
         15, 1300, 3000,  952,    5,  749,  541,  330,  393,  517,  770,
        409,  170,  125,  283,  342,  363,  580,  105,  217,   24,  141,
         10,  427,  158,  426,    4,  666,  181,  324,  979, 1400,  302,
        751,  298,  411,  944,    2,  947,  292,  349,  621,    1, 2800,
        338,  287,  261,  218, 1800,  240,  279,  229,  188,  315,  664,
        613,  190,  706,  127,  462,  386,  695,  491,  167,  281,  250,
        307,   95,  231,  174,  680,  633,  221,  348,  602,  183,  653,
        195,  164,  151,  258, 8400,  343,  419,  655,  136,  399,  531,
        357,  228,  385,  312,  340,  238,  487,  355,  499, 4300,  296,
        515,  943, 1200,  903,  335,  191,  594,  267,  617,  516,  504,
        331,  652,  410,  550,  473,  442,  344,  208, 1000, 2500,  273,
        485,  826,  192,  405,  941,  477,  644,  303,  417, 6000,    0])

In [16]:
#Checking if any null values in df
df.isnull().sum().sum()

0

In [17]:
#Is column 'ID' unique? 
df['ID'].is_unique

True

In [18]:
#'ID' column in df is unique, so we can set it as index of df
df.set_index('ID', inplace=True)

In [19]:
#Showing result
df

,Name,LongName,photoUrl,playerUrl,Nationality,Age,OVA,POT,Club,Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
ID,,,,,,,,,,,,,,,,,,,,,
158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,...,Medium,Low,5 ★,85,92,91,95,38,65,771
20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,...,High,Low,5 ★,89,93,81,89,35,77,562
200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,...,High,High,4 ★,76,86,93,88,64,78,207
190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,...,High,Medium,5 ★,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,\n\n\n\nWuhan Zall,2018 ~ 2022,...,Medium,Medium,1 ★,64,28,26,38,48,51,0
258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,\n\n\n\nOldham Athletic,2020 ~ 2021,...,Medium,Medium,1 ★,64,40,48,49,35,45,0
252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,\n\n\n\nDerry City,2019 ~ 2020,...,Medium,Medium,1 ★,63,39,44,46,40,53,0
243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,\n\n\n\nDalian YiFang FC,2020 ~ 2022,...,Medium,Medium,1 ★,58,49,41,49,30,44,0
252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,\n\n\n\nDalian YiFang FC,2019 ~ 2023,...,Medium,Medium,1 ★,62,22,39,42,45,55,0

In [20]:
#Dropping unnecesary columns as 'Name', 'photoUrl' and 'playerUrl'
df.drop(columns=['Name','photoUrl','playerUrl'],inplace=True)

In [21]:
#Renaming column 'LongName' to 'Name'
df.rename(columns={'LongName':'Name'}, inplace=True)

In [22]:
#Showing results
df

,Name,Nationality,Age,OVA,POT,Club,Contract,Positions,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
ID,,,,,,,,,,,,,,,,,,,,,
158023,Lionel Messi,Argentina,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,...,Medium,Low,5 ★,85,92,91,95,38,65,771
20801,C. Ronaldo dos Santos Aveiro,Portugal,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",187cm,83kg,...,High,Low,5 ★,89,93,81,89,35,77,562
200389,Jan Oblak,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,GK,188cm,87kg,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
192985,Kevin De Bruyne,Belgium,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,...,High,High,4 ★,76,86,93,88,64,78,207
190871,Neymar da Silva Santos Jr.,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,...,High,Medium,5 ★,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247223,Ao Xia,China PR,21,47,55,\n\n\n\nWuhan Zall,2018 ~ 2022,CB,178cm,66kg,...,Medium,Medium,1 ★,64,28,26,38,48,51,0
258760,Ben Hough,England,17,47,67,\n\n\n\nOldham Athletic,2020 ~ 2021,CM,175cm,65kg,...,Medium,Medium,1 ★,64,40,48,49,35,45,0
252757,Ronan McKinley,England,18,47,65,\n\n\n\nDerry City,2019 ~ 2020,CM,179cm,74kg,...,Medium,Medium,1 ★,63,39,44,46,40,53,0
243790,Zhen'ao Wang,China PR,20,47,57,\n\n\n\nDalian YiFang FC,2020 ~ 2022,RW,175cm,69kg,...,Medium,Medium,1 ★,58,49,41,49,30,44,0
252520,Xiao Zhou,China PR,21,47,57,\n\n\n\nDalian YiFang FC,2019 ~ 2023,"CB, LB",188cm,75kg,...,Medium,Medium,1 ★,62,22,39,42,45,55,0

In [23]:
#Stripping leading and trailing spaces from the column values
for i in df.columns:
    if df[i].dtype == 'object':
        df[i] = df[i].str.strip()

In [24]:
#Showing results
df

,Name,Nationality,Age,OVA,POT,Club,Contract,Positions,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
ID,,,,,,,,,,,,,,,,,,,,,
158023,Lionel Messi,Argentina,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,...,Medium,Low,5 ★,85,92,91,95,38,65,771
20801,C. Ronaldo dos Santos Aveiro,Portugal,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187cm,83kg,...,High,Low,5 ★,89,93,81,89,35,77,562
200389,Jan Oblak,Slovenia,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188cm,87kg,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
192985,Kevin De Bruyne,Belgium,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,...,High,High,4 ★,76,86,93,88,64,78,207
190871,Neymar da Silva Santos Jr.,Brazil,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,...,High,Medium,5 ★,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247223,Ao Xia,China PR,21,47,55,Wuhan Zall,2018 ~ 2022,CB,178cm,66kg,...,Medium,Medium,1 ★,64,28,26,38,48,51,0
258760,Ben Hough,England,17,47,67,Oldham Athletic,2020 ~ 2021,CM,175cm,65kg,...,Medium,Medium,1 ★,64,40,48,49,35,45,0
252757,Ronan McKinley,England,18,47,65,Derry City,2019 ~ 2020,CM,179cm,74kg,...,Medium,Medium,1 ★,63,39,44,46,40,53,0
243790,Zhen'ao Wang,China PR,20,47,57,Dalian YiFang FC,2020 ~ 2022,RW,175cm,69kg,...,Medium,Medium,1 ★,58,49,41,49,30,44,0
252520,Xiao Zhou,China PR,21,47,57,Dalian YiFang FC,2019 ~ 2023,"CB, LB",188cm,75kg,...,Medium,Medium,1 ★,62,22,39,42,45,55,0

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18979 entries, 158023 to 252520
Data columns (total 73 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Name              18979 non-null  object
 1   Nationality       18979 non-null  object
 2   Age               18979 non-null  int64
 3   OVA               18979 non-null  int64
 4   POT               18979 non-null  int64
 5   Club              18979 non-null  object
 6   Contract          18979 non-null  object
 7   Positions         18979 non-null  object
 8   Height            18979 non-null  object
 9   Weight            18979 non-null  object
 10  Preferred Foot    18979 non-null  object
 11  BOV               18979 non-null  int64
 12  Best Position     18979 non-null  object
 13  Joined            18979 non-null  object
 14  Loan Date End     18979 non-null  object
 15  Value             18979 non-null  object
 16  Wage              18979 non-null  object
 17  Release Clause    18979 non-null  object
 18  Attacking         18979 non-null  int64
 19  Crossing          18979 non-null  int64
 20  Finishing         18979 non-null  int64
 21  Heading Accuracy  18979 non-null  int64
 22  Short Passing     18979 non-null  int64
 23  Volleys           18979 non-null  int64
 24  Skill             18979 non-null  int64
 25  Dribbling         18979 non-null  int64
 26  Curve             18979 non-null  int64
 27  FK Accuracy       18979 non-null  int64
 28  Long Passing      18979 non-null  int64
 29  Ball Control      18979 non-null  int64
 30  Movement          18979 non-null  int64
 31  Acceleration      18979 non-null  int64
 32  Sprint Speed      18979 non-null  int64
 33  Agility           18979 non-null  int64
 34  Reactions         18979 non-null  int64
 35  Balance           18979 non-null  int64
 36  Power             18979 non-null  int64
 37  Shot Power        18979 non-null  int64
 38  Jumping           18979 non-null  int64
 39  Stamina           18979 non-null  int64
 40  Strength          18979 non-null  int64
 41  Long Shots        18979 non-null  int64
 42  Mentality         18979 non-null  int64
 43  Aggression        18979 non-null  int64
 44  Interceptions     18979 non-null  int64
 45  Positioning       18979 non-null  int64
 46  Vision            18979 non-null  int64
 47  Penalties         18979 non-null  int64
 48  Composure         18979 non-null  int64
 49  Defending         18979 non-null  int64
 50  Marking           18979 non-null  int64
 51  Standing Tackle   18979 non-null  int64
 52  Sliding Tackle    18979 non-null  int64
 53  Goalkeeping       18979 non-null  int64
 54  GK Diving         18979 non-null  int64
 55  GK Handling       18979 non-null  int64
 56  GK Kicking        18979 non-null  int64
 57  GK Positioning    18979 non-null  int64
 58  GK Reflexes       18979 non-null  int64
 59  Total Stats       18979 non-null  int64
 60  Base Stats        18979 non-null  int64
 61  W/F               18979 non-null  object
 62  SM                18979 non-null  object
 63  A/W               18979 non-null  object
 64  D/W               18979 non-null  object
 65  IR                18979 non-null  object
 66  PAC               18979 non-null  int64
 67  SHO               18979 non-null  int64
 68  PAS               18979 non-null  int64
 69  DRI               18979 non-null  int64
 70  DEF               18979 non-null  int64
 71  PHY               18979 non-null  int64
 72  Hits              18979 non-null  int32
dtypes: int32(1), int64(53), object(19)
memory usage: 10.6+ MB

In [26]:
#Loop through each column and print unique values
for column in df.columns:
    print(f"Unique values in {column}: {df[column].unique()}\n\n\n")

Unique values in Name: ['Lionel Messi' 'C. Ronaldo dos Santos Aveiro' 'Jan Oblak' ...
 'Ronan McKinley' "Zhen'ao Wang" 'Xiao Zhou']



Unique values in Nationality: ['Argentina' 'Portugal' 'Slovenia' 'Belgium' 'Brazil' 'Poland' 'Egypt'
 'France' 'Germany' 'Netherlands' 'Senegal' 'Spain' 'England' 'Scotland'
 'Korea Republic' 'Costa Rica' 'Italy' 'Gabon' 'Croatia' 'Uruguay'
 'Switzerland' 'Serbia' 'Slovakia' 'Morocco' 'Algeria' 'Denmark' 'Hungary'
 'Bosnia Herzegovina' 'Nigeria' 'Cameroon' 'Norway' 'Ghana' 'Mexico'
 'Austria' 'Albania' 'Colombia' 'Chile' 'Ivory Coast' 'Greece' 'Finland'
 'Wales' 'Sweden' 'Togo' 'Czech Republic' 'Russia' 'Venezuela' 'Canada'
 'United States' 'Guinea' 'Montenegro' 'Israel' 'Republic of Ireland'
 'Ukraine' 'Turkey' 'Ecuador' 'Jamaica' 'DR Congo' 'Australia' 'China PR'
 'Armenia' 'Northern Ireland' 'North Macedonia' 'Kosovo' 'Mali' 'Peru'
 'Central African Republic' 'Iceland' 'Burkina Faso' 'Paraguay' 'Japan'
 'Romania' 'New Zealand' 'Iran' 'Angola' 'Tunisia' 'Syria'
 'Dominican Republic' 'Cape Verde' 'Equatorial Guinea' 'Kenya' 'Georgia'
 'Panama' 'Zambia' 'Tanzania' 'Zimbabwe' 'Congo' 'South Africa' 'Moldova'
 'Mozambique' 'Iraq' 'Guinea Bissau' 'Honduras' 'Cuba' 'Cyprus'
 'Lithuania' 'Estonia' 'Madagascar' 'Benin' 'Curacao' 'Saudi Arabia'
 'Gambia' 'Uzbekistan' 'Chad' 'United Arab Emirates'
 'Saint Kitts and Nevis' 'Libya' 'Sierra Leone' 'Philippines' 'Liberia'
 'Bulgaria' 'Comoros' 'Namibia' 'Luxembourg' 'Trinidad & Tobago' 'Bermuda'
 'Thailand' 'Burundi' 'New Caledonia' 'Puerto Rico' 'Bolivia' 'Kazakhstan'
 'Antigua & Barbuda' 'Latvia' 'Malawi' 'Montserrat' 'São Tomé & Príncipe'
 'El Salvador' 'Mauritania' 'Jordan' 'Eritrea' 'Aruba' 'Uganda'
 'Chinese Taipei' 'Azerbaijan' 'Afghanistan' 'Faroe Islands' 'Haiti'
 'Sudan' 'Grenada' 'Lebanon' 'Guam' 'Palestine' 'Belarus' 'Guyana'
 'Rwanda' 'Liechtenstein' 'Saint Lucia' 'Papua New Guinea' 'India'
 'Ethiopia' 'Belize' 'Andorra' 'Guatemala' 'Malta' 'Niger' 'Korea DPR'
 'Barbados' 'Macau' 'South Sudan' 'Singapore' 'Hong Kong' 'Nicaragua'
 'Malaysia' 'Indonesia']



Unique values in Age: [33 35 27 29 28 31 21 34 32 25 26 30 20 24 22 23 19 38 42 36 37 18 17 39
 40 41 16 43 53]



Unique values in OVA: [93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76 75 74 73 72 71 70
 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47]



Unique values in POT: [93 92 91 90 95 89 88 87 86 85 84 83 82 81 80 79 78 77 76 75 74 73 72 71
 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47]



Unique values in Club: ['FC Barcelona' 'Juventus' 'Atlético Madrid' 'Manchester City'
 'Paris Saint-Germain' 'FC Bayern München' 'Liverpool' 'Real Madrid'
 'Chelsea' 'Tottenham Hotspur' 'Inter' 'Napoli' 'Borussia Dortmund'
 'Manchester United' 'Arsenal' 'Lazio' 'Leicester City'
 'Borussia Mönchengladbach' 'Real Sociedad' 'Atalanta'
 'Olympique Lyonnais' 'Milan' 'Villarreal CF' 'RB Leipzig' 'Cagliari'
 'Ajax' 'SL Benfica' 'AS Monaco' 'Wolverhampton Wanderers' 'Everton'
 'Fiorentina' 'FC Porto' 'RC Celta' 'Torino' 'Sevilla FC' 'Grêmio'
 'Real Betis' 'Roma' 'Newcastle United' 'Eintracht Frankfurt'
 'Valencia CF' 'Medipol Başakşehir FK' 'Inter Miami' 'Bayer 04 Leverkusen'
 'Levante UD' 'Crystal Palace' 'Athletic Club de Bilbao'
 'Shanghai SIPG FC' 'VfL Wolfsburg' 'Guangzhou Evergrande Taobao FC'
 'Al Shabab' 'Olympique de Marseille' 'Los Angeles FC'
 'Beijing Sinobo Guoan FC' 'Getafe CF' 'SV Werder Bremen'
 'TSG 1899 Hoffenheim' 'LOSC Lille' 'Deportivo Alavés' 'Burnley'
 'Leeds United' 'Fulham' 'PFC CSKA Moscow' 'Genoa' 'Galatasaray SK'
 'Atlanta United' 'Atlético Mineiro' 'Flamengo' 'Palmeiras' 'No Club'
 'São Paulo' 'West Ham United' 'SD Eibar' 'River Plate' 'OGC Nice'
 'Real Valladolid CF' 'Sporting CP' 'PSV' 'Feyenoord' 'Club Brugge KV'
 'Shakhtar Donetsk' 'Vissel Kobe' 'Boca Juniors' '1. FC Union Berlin'
 'Dalian YiFang FC' 'AS Saint-Étienne' 'Sassuolo' 'Tigres U.A.N.L.'
 'Dinamo Zagreb' 'Dynamo Kyiv' 'Fluminense' 'Udinese' 'Aston Villa'
 'Stade Rennais FC' 'Beşiktaş JK' 'Brighton & Hove Albion'
 'Hebei China Fortune FC' 'Southampton' 'Lokomotiv Moscow'
 'Jiangsu Suning FC' 'Al Hilal' 'West Bromwich Albion' 'Fenerbahçe SK'
 'FC Groningen' 'Guangzhou R&F FC' 'Orlando City SC' 'Sampdoria'
 'Stade de Reims' 'Sheffield United' 'Santos' 'Internacional' 'Coritiba'
 'CA Osasuna' 'LA Galaxy' 'Al Nassr' 'SC Freiburg' 'SC Braga'
 'Olympiacos CFP' 'Toronto FC' 'Granada CF' 'FC Schalke 04'
 'RC Strasbourg Alsace' 'Hertha BSC' 'AZ Alkmaar' 'Seattle Sounders FC'
 'Montpellier HSC' 'Shanghai Greenland Shenhua FC' 'Hamburger SV'
 'Girona FC' 'Racing Club' 'Portland Timbers' 'FC Girondins de Bordeaux'
 'Watford' 'Estudiantes de La Plata' 'Club América' 'Vitória Guimarães'
 'SK Slavia Praha' 'Trabzonspor' 'RCD Espanyol' 'FC Nantes' 'Angers SCO'
 'Cruz Azul' 'BSC Young Boys' 'Club León' 'Spartak Moscow' 'Sivasspor'
 'Elche CF' 'FC Augsburg' 'Wuhan Zall' 'Parma' 'Royal Antwerp FC'
 'Monterrey' 'San Lorenzo de Almagro' 'AC Monza' 'Club Atlético Lanús'
 'SD Huesca' 'Derby County' 'Kayserispor' 'RSC Anderlecht' 'CD Leganés'
 'Vélez Sarsfield' 'Stade Brestois 29' 'Tianjin TEDA FC' 'Birmingham City'
 'Hellas Verona' '1. FC Köln' 'Al Wehda' 'Bournemouth' 'Alanyaspor'
 'Bologna' 'Amiens SC' 'Celtic' 'Shijiazhuang Ever Bright F.C.'
 'Club Atlas' 'Al Ahli' 'Norwich City' 'Fatih Karagümrük S.K.'
 'Club Tijuana' 'Universidad Católica' 'Goiás' 'Benevento' 'Independiente'
 'Qingdao Huanghai F.C.' 'Brentford' 'AEK Athens' 'Racing Club de Lens'
 'Olimpia Asunción' 'Shenzhen FC' 'Çaykur Rizespor' 'KAA Gent'
 'New England Revolution' 'Cádiz CF' '1. FSV Mainz 05' 'Vasco da Gama'
 'FC Midtjylland' 'Al Ain FC' 'Santos Laguna' 'SPAL' 'Perth Glory'
 'FC Utrecht' 'Montreal Impact' 'UD Almería' 'Fortaleza' 'Spezia'
 'FC Basel 1893' 'FC København' 'Godoy Cruz' 'Deportivo Toluca'
 'Nacional de Montevideo' 'Aalborg BK' 'Rio Ave FC' 'FC Metz'
 'Chongqing Dangdai Lifan FC SWM Team' 'Rosenborg BK'
 'FC Red Bull Salzburg' 'Botafogo' 'DSC Arminia Bielefeld'
 'Club Athletico Paranaense' 'RCD Mallorca' 'Pachuca' 'Swansea City'
 'KRC Genk' 'En Avant de Guingamp' 'Lecce' 'Nîmes Olympique' 'Colo-Colo'
 'Stade Malherbe Caen' 'Columbus Crew SC' 'Junior FC' 'VfB Stuttgart'
 'Moreirense FC' 'Rangers FC' 'Malmö FF' 'Shandong Luneng TaiShan FC'
 'Sparta Praha' 'Hatayspor' 'Chicago Fire' 'Toulouse Football Club'
 'FC Seoul' 'Antalyaspor' 'Deportivo Cali' 'Kaizer Chiefs' 'Real Zaragoza'
 'Atlético Clube Goianiense' 'Puebla FC' 'Fortuna Düsseldorf'
 'Western United FC' 'Astra Giurgiu' 'Henan Jianye FC' 'Bahia' 'Famalicão'
 'Atiker Konyaspor' 'Peñarol' 'DC United' 'New York City FC'
 'Argentinos Juniors' 'U.N.A.M.' 'Minnesota United FC' 'Nottingham Forest'
 'Independiente del Valle' 'Defensa y Justicia' 'Philadelphia Union'
 "Newell's Old Boys" 'Rosario Central' 'Atlético de San Luis' 'FC Dallas'
 'Denizlispor' 'Yeni Malatyaspor' 'Club Atlético Colón' 'Houston Dynamo'
 'Millwall' 'Clube Sport Marítimo' 'MKE Ankaragücü' 'Guadalajara'
 'Boavista FC' 'Sporting Kansas City' 'Atlético Nacional' 'CD Lugo'
 'New York Red Bulls' 'PAOK' 'SC Heerenveen' 'Daegu FC'
 'Preston North End' 'Damac FC' 'Brescia' 'VfL Bochum 1848'
 'Vancouver Whitecaps FC' 'SV Sandhausen' 'Royal Excel Mouscron'
 'Dijon FCO' 'Molde FK' 'Panathinaikos FC' 'LASK Linz' 'Ulsan Hyundai FC'
 'Real Salt Lake' 'FC Luzern' 'Viktoria Plzeň' 'Orlando Pirates'
 'Al Ittihad' '1. FC Nürnberg' 'Standard de Liège' 'Rayo Vallecano'
 'Club Libertad' 'Jeonbuk Hyundai Motors' 'Western Sydney Wanderers'
 'Unión de Santa Fe' 'FC Sion' 'Sydney FC' 'Hannover 96'
 'Real Sporting de Gijón' 'FC Cincinnati' 'ESTAC Troyes'
 'San Jose Earthquakes' 'Club Guaraní' 'FC Lorient' 'Gençlerbirliği SK'
 'Sporting de Charleroi' 'Wisła Kraków' 'Al Taawoun' 'Reading'
 'Gazişehir Gaziantep F.K.' 'Blackburn Rovers' 'Kashiwa Reysol'
 'FK Bodø/Glimt' 'Willem II' 'Vitesse' 'Gil Vicente FC' 'SønderjyskE'
 'Yokohama F. Marinos' 'FC St. Gallen' 'Club Atlético Aldosivi'
 'Göztepe SK' 'Holstein Kiel' 'FC Juárez' 'FCSB (Steaua)' 'Ettifaq FC'
 'KAS Eupen' 'FC Tokyo' 'Melbourne City FC' 'Universitatea Craiova'
 'CD Tondela' 'Wolfsberger AC' 'Ceará Sporting Club'
 'River Plate Asunción' 'Stoke City' 'Paris FC' 'IFK Norrköping' 'Crotone'
 'Cardiff City' 'América de Cali' 'Al Faisaly' 'Independiente Medellín'
 'Portimonense SC' 'CD Tenerife' 'Heracles Almelo' 'Nashville SC'
 'SK Rapid Wien' 'Kawasaki Frontale' 'Club Necaxa' 'Chievo Verona'
 'Lech Poznań' 'AIK' 'FK Austria Wien' 'Querétaro' '1. FC Heidenheim 1846'
 'Legia Warszawa' 'Club Atlético Banfield' 'Os Belenenses'
 'Huddersfield Town' 'KSV Cercle Brugge' 'LDU Quito'
 'Gimnasia y Esgrima La Plata' 'Gamba Osaka' 'Middlesbrough' 'Servette FC'
 'Empoli' 'Real Oviedo' 'Kasimpaşa SK' 'CFR Cluj' 'Millonarios FC'
 'FC Paços de Ferreira' 'Sint-Truidense VV' 'AD Alcorcón'
 'Colorado Rapids' 'Dinamo Bucureşti' 'Cerezo Osaka' 'FC Emmen'
 'Sheffield Wednesday' 'FC Erzgebirge Aue' 'Raków Częstochowa'
 'Atlético Tucumán' 'SV Darmstadt 98' 'Bristol City' 'Oud-Heverlee Leuven'
 'Barnsley' 'Queens Park Rangers' 'Sangju Sangmu FC' 'Helsingborgs IF'
 'AC Ajaccio' 'Oceânico FC' 'Club Atlético Talleres' 'Al Hazem'
 'SC Paderborn 07' 'Club Atlético Huracán' 'KV Kortrijk' 'El Nacional'
 'Mazatlán FC' 'Aberdeen' 'CD Mirandés' 'SV Zulte-Waregem' 'Piast Gliwice'
 'Djurgårdens IF' 'Central Córdoba' 'Wellington Phoenix'
 'Deportivo Binacional' 'Patronato' 'SpVgg Greuther Fürth' 'IFK Göteborg'
 'FC Cartagena' 'Santa Clara' 'FC Twente' 'Farense' 'ADO Den Haag'
 'AJ Auxerre' 'Al Fateh' 'Valenciennes FC' 'Hokkaido Consadole Sapporo'
 'FC St. Pauli' 'Albacete BP' '1. FC Kaiserslautern' 'Al Fayha'
 'Incheon United FC' 'KV Mechelen' 'Pohang Steelers' 'CD Nacional'
 'Unión La Calera' 'BB Erzurumspor' 'Kashima Antlers' 'Arsenal de Sarandí'
 'HJK Helsinki' 'Karlsruher SC' 'Aarhus GF' 'FC Zürich'
 'Barcelona Sporting Club' 'SG Dynamo Dresden' 'Sanfrecce Hiroshima'
 'Al Raed' 'SD Ponferradina' 'Brøndby IF' 'Lechia Gdańsk' 'FC Viitorul'
 'SK Sturm Graz' 'IF Elfsborg' 'Gangwon FC' 'Melgar FBC'
 'Club Atlético Grau' 'Jagiellonia Białystok' 'Waasland-Beveren'
 'VfL Osnabrück' 'Nagoya Grampus' 'CF Fuenlabrada' 'Shamrock Rovers'
 'Shimizu S-Pulse' 'RKC Waalwijk' 'Vålerenga Fotball' 'Clermont Foot 63'
 'FC Ingolstadt 04' 'FC Würzburger Kickers' 'Górnik Zabrze'
 'Charlton Athletic' 'Beerschot AC' 'Coquimbo Unido' 'Viktoria Köln'
 'Hull City' 'Málaga CF' 'FC Nordsjælland' 'UD Las Palmas' 'VVV-Venlo'
 'GwangJu FC' 'Chamois Niortais Football Club' 'FC Lugano' 'Cusco FC'
 'Sparta Rotterdam' 'Sol de América' 'PEC Zwolle' 'Pogoń Szczecin'
 'Doncaster Rovers' 'Kristiansund BK' 'Liverpool Fútbol Club'
 'Club Bolívar' 'Urawa Red Diamonds' 'SK Brann' 'Eintracht Braunschweig'
 'Nacional Asunción' 'Melbourne Victory' 'Kilmarnock' 'Dundalk'
 'SSV Jahn Regensburg' 'Abha Club' 'Club Atlético Tigre'
 'Suwon Samsung Bluewings' 'Shonan Bellmare' 'SD Aucas' 'Emelec'
 'Fortuna Sittard' 'La Berrichonne de Châteauroux' 'Śląsk Wrocław'
 'Coventry City' 'Sunderland' 'Alianza Lima' 'Hammarby IF' 'Cracovia'
 'CE Sabadell FC' 'Oita Trinita' 'BK Häcken' 'Luton Town' 'Le Havre AC'
 'IK Sirius' 'Zagłębie Lubin' 'Grenoble Foot 38' 'Macarthur FC'
 'Rodez Aveyron Football' 'Vegalta Sendai' 'Motherwell'
 'SV Wehen Wiesbaden' 'Audax Italiano' 'Gaz Metan Mediaş' 'Portsmouth'
 'Hibernian' 'Always Ready' 'UD Logroñés' 'FC Voluntari' 'FC Hermannstadt'
 'AS Nancy Lorraine' 'Rotherham United' 'Fleetwood Town'
 'Jorge Wilstermann' 'Odense Boldklub' 'MSV Duisburg'
 'FC Sochaux-Montbéliard' 'Milton Keynes Dons' 'River Plate Montevideo'
 'Delfín SC' 'Universidad Católica del Ecuador' 'Deportivo Pasto'
 'KV Oostende' 'Club Plaza Colonia' 'Wigan Athletic' 'FC Botoşani'
 'C.D. Castellón' 'SCR Altach' 'Örebro SK' 'TSV Hartberg' 'Stabæk Fotball'
 'Wycombe Wanderers' 'St. Johnstone FC' 'Oxford United' 'Lincoln City'
 'Randers FC' 'Viking FK' 'FC Chambly Oise' 'Dundee United'
 'Oriente Petrolero' 'Odds BK' 'Nacional Potosí' 'Sepsi OSK'
 'FC Hansa Rostock' 'Lyngby BK' 'SpVgg Unterhaching' 'Brisbane Roar'
 'Seongnam FC' 'SV Ried' 'CD Huachipato' 'WSG Tirol'
 'Podbeskidzie Bielsko-Biała' 'Peterborough United' 'Club Blooming'
 'Wisła Płock' 'Busan IPark' 'FSV Zwickau' 'Mjøndalen IF' 'Vejle Boldklub'
 'Pau FC' 'FC Lausanne-Sport' 'Estudiantes de Mérida' 'Sagan Tosu'
 'SV Waldhof Mannheim' 'Sport Huancayo' 'Hallescher FC' 'Kalmar FF'
 'St. Mirren' 'SKN St. Pölten' 'Sarpsborg 08 FF' 'Shrewsbury'
 'TSV 1860 München' 'SV Meppen' 'Ipswich Town' 'IK Start'
 'Adelaide United' 'Stal Mielec' 'Centro Atlético Fénix' 'Newcastle Jets'
 'Livingston FC' 'AC Mineros de Guayana' 'AFC Wimbledon' 'Burton Albion'
 'Al Adalah' 'Warta Poznań' 'USL Dunkerque' 'Bristol Rovers' 'UTA Arad'
 'Östersunds FK' 'Sportivo Luqueño' 'Politehnica Iaşi' 'Salford City'
 'Central Coast Mariners' 'Caracas FC' 'AC Horsens' 'Plymouth Argyle'
 'Aalesunds FK' 'Crewe Alexandra' 'Chindia Târgovişte' 'Oldham Athletic'
 'Yokohama FC' 'Blackpool' 'Northampton Town' 'Bayern München II'
 'FK Haugesund' 'KFC Uerdingen 05' 'Forest Green Rovers' 'Cheltenham Town'
 'Strømsgodset IF' 'Mjällby AIF' 'Exeter City' 'Cambridge United'
 'Grimsby Town' 'FC Vaduz' 'Türkgücü München' 'VfB Lübeck'
 'Bolton Wanderers' 'Bradford City' '1. FC Magdeburg'
 'FC Admira Wacker Mödling' 'Hamilton Academical FC' 'Aragua FC'
 'Accrington Stanley' 'Swindon Town' 'Carlisle United' 'FC Argeș'
 'Port Vale' 'Academica Clinceni' 'Rochdale' 'Gillingham'
 'Tranmere Rovers' 'Southend United' '1. FC Saarbrücken'
 'Colchester United' 'Mansfield Town' 'Falkenbergs FF' 'SC Verl'
 'Varbergs BoIS' 'Crawley Town' 'Sandefjord Fotball' 'Newport County'
 'Bohemian FC' 'Ross County FC' 'Scunthorpe United' 'Morecambe' 'Walsall'
 'Leyton Orient' 'Stevenage' 'Barrow' 'Derry City' 'Llaneros de Guanare'
 'Sligo Rovers' 'Zamora FC' "St. Patrick's Athletic" 'Cork City'
 'Shelbourne FC' 'Harrogate Town' 'Waterford FC' 'Finn Harps']



Unique values in Contract: ['2004 ~ 2021' '2018 ~ 2022' '2014 ~ 2023' '2015 ~ 2023' '2017 ~ 2022'
 '2017 ~ 2023' '2018 ~ 2024' '2014 ~ 2022' '2018 ~ 2023' '2016 ~ 2023'
 '2013 ~ 2023' '2011 ~ 2023' '2009 ~ 2022' '2005 ~ 2021' '2011 ~ 2021'
 '2015 ~ 2022' '2017 ~ 2024' '2010 ~ 2024' '2012 ~ 2021' '2019 ~ 2024'
 '2015 ~ 2024' '2017 ~ 2025' '2020 ~ 2025' '2019 ~ 2023' '2008 ~ 2023'
 '2015 ~ 2021' '2020 ~ 2022' '2012 ~ 2022' '2016 ~ 2025' '2013 ~ 2022'
 '2011 ~ 2022' '2012 ~ 2024' '2016 ~ 2021' '2012 ~ 2023' '2008 ~ 2022'
 '2019 ~ 2022' '2017 ~ 2021' '2013 ~ 2024' '2020 ~ 2024' '2010 ~ 2022'
 '2020 ~ 2021' '2011 ~ 2024' '2020 ~ 2023' '2014 ~ 2024' '2013 ~ 2026'
 '2016 ~ 2022' '2010 ~ 2021' '2013 ~ 2021' '2019 ~ 2025' '2018 ~ 2025'
 '2016 ~ 2024' '2018 ~ 2021' '2009 ~ 2024' '2007 ~ 2022'
 'Jun 30, 2021 On Loan' '2009 ~ 2021' '2019 ~ 2021' '2019 ~ 2026' 'Free'
 '2012 ~ 2028' '2010 ~ 2023' '2014 ~ 2021' '2015 ~ 2025' '2014 ~ 2026'
 '2012 ~ 2025' '2017 ~ 2020' '2002 ~ 2022' '2020 ~ 2027' '2013 ~ 2025'
 'Dec 31, 2020 On Loan' '2019 ~ 2020' '2011 ~ 2025' '2016 ~ 2020'
 '2007 ~ 2021' '2020 ~ 2026' '2010 ~ 2025' '2009 ~ 2023' '2008 ~ 2021'
 '2020 ~ 2020' '2016 ~ 2026' 'Jan 30, 2021 On Loan' '2012 ~ 2020'
 '2014 ~ 2025' 'Jun 30, 2022 On Loan' '2015 ~ 2020' 'May 31, 2021 On Loan'
 '2018 ~ 2020' '2014 ~ 2020' '2013 ~ 2020' '2006 ~ 2024'
 'Jul 5, 2021 On Loan' 'Dec 31, 2021 On Loan' '2004 ~ 2025' '2011 ~ 2020'
 'Jul 1, 2021 On Loan' 'Jan 1, 2021 On Loan' '2006 ~ 2023'
 'Aug 31, 2021 On Loan' '2006 ~ 2021' '2005 ~ 2023' '2003 ~ 2020'
 '2009 ~ 2020' '2002 ~ 2020' '2005 ~ 2020' '2005 ~ 2022'
 'Jan 31, 2021 On Loan' '2010 ~ 2020' 'Dec 30, 2021 On Loan' '2008 ~ 2020'
 '2007 ~ 2020' '2003 ~ 2021' 'Jun 23, 2021 On Loan' 'Jan 3, 2021 On Loan'
 'Nov 27, 2021 On Loan' '2002 ~ 2021' 'Jan 17, 2021 On Loan'
 'Jun 30, 2023 On Loan' '1998 ~ 2021' '2003 ~ 2022' '2007 ~ 2023'
 'Jul 31, 2021 On Loan' 'Nov 22, 2020 On Loan' 'May 31, 2022 On Loan'
 '2006 ~ 2020' 'Dec 30, 2020 On Loan' '2007 ~ 2025' 'Jan 4, 2021 On Loan'
 'Nov 30, 2020 On Loan' '2004 ~ 2020' '2009 ~ 2025' 'Aug 1, 2021 On Loan']



Unique values in Positions: ['RW, ST, CF' 'ST, LW' 'GK' 'CAM, CM' 'LW, CAM' 'ST' 'RW' 'ST, LW, RW'
 'CB' 'LW' 'CDM' 'CF, ST' 'LW, RW' 'CDM, CM' 'CDM, RB' 'CF, CAM' 'LW, ST'
 'CM' 'ST, CF, LW' 'RM, LM, CAM' 'RB' 'RW, CAM, CM' 'LB' 'LM, CF' 'CF'
 'RW, LW' 'CAM, RM, RW' 'CM, CDM' 'CAM, CF, ST' 'CM, CDM, CAM'
 'CF, LW, CAM' 'CAM, RM, CF' 'LM, ST' 'RM, LM, RW' 'LM' 'CAM, RW'
 'CB, CDM' 'RW, RM' 'LW, CF' 'CM, RM, LM' 'LB, LM' 'CAM, CM, RM'
 'CAM, CM, CF' 'CAM, CF' 'LM, RM, LW' 'LM, LB, CM' 'CM, LM, LB' 'RM, RW'
 'RM, CM' 'CAM, CM, LW' 'CB, LB' 'RM, RB' 'ST, RW' 'LM, RW, LW' 'RB, LB'
 'RB, RM' 'RM' 'LM, RM, CF' 'CAM, RM' 'RB, RWB' 'CDM, CB, CM'
 'CAM, RM, ST' 'LM, LW, RM' 'CM, CAM' 'ST, RM, CF' 'LM, RM' 'RM, CF'
 'LM, LWB' 'RW, RM, CF' 'RB, CM' 'LW, CAM, RW' 'CAM, LW, CM'
 'CM, CAM, CDM' 'RW, LW, CAM' 'CM, CAM, LM' 'CM, RM, ST' 'CDM, CM, RB'
 'ST, CAM' 'CAM, LW, ST' 'LB, CB, LWB' 'RM, ST' 'CB, CDM, LB' 'RWB, RM'
 'CM, LM, RM' 'RB, CDM, CM' 'RW, LW, RM' 'LM, LW' 'CM, LM' 'LM, LB'
 'RM, LM, CF' 'LB, LM, RM' 'CDM, CM, CAM' 'ST, LW, RM' 'CAM, CM, ST'
 'ST, CF' 'LWB, LB' 'LW, RW, LM' 'RM, RW, ST' 'LWB' 'CF, ST, CAM'
 'LM, CAM, RM' 'RB, CB' 'ST, LM' 'RW, CAM' 'LM, CAM' 'RWB, RB'
 'ST, RW, LW' 'CAM' 'RB, RM, RW' 'LB, LWB' 'RM, CAM' 'CAM, ST' 'CDM, CB'
 'CF, LM, LW' 'CAM, LM, LW' 'LW, RW, CAM' 'CB, RB' 'RB, CB, RWB'
 'LM, LW, ST' 'LW, ST, CM' 'RM, CAM, CM' 'CB, RB, RWB' 'RW, ST, LW'
 'LW, CAM, CM' 'CM, LM, CDM' 'LB, LM, LWB' 'CB, LB, RB' 'CAM, LW'
 'RWB, RB, RM' 'CF, CAM, ST' 'RM, CAM, RW' 'RW, ST' 'LW, LM' 'RB, RM, CM'
 'ST, CAM, RW' 'CM, RB, LB' 'CAM, LM, RM' 'RB, RW' 'LM, CM' 'RM, LM, CM'
 'CDM, CM, CB' 'CM, CF' 'CF, LW, RW' 'ST, RM' 'CAM, CM, CDM' 'LB, CB'
 'RW, RWB' 'ST, LM, RM' 'RM, RWB, RB' 'LM, ST, CAM' 'CAM, ST, CF' 'LW, CM'
 'RB, RWB, LB' 'RM, LM' 'CM, CAM, RM' 'ST, LW, CAM' 'RM, RW, CAM'
 'CM, CDM, RM' 'RB, RM, RWB' 'CDM, CB, LB' 'CAM, ST, LM' 'LM, CM, RM'
 'CF, RW' 'CAM, RM, LW' 'CM, RM, CDM' 'LB, LWB, LM' 'LW, RW, CF'
 'LW, LM, CAM' 'LWB, LW, LB' 'CDM, CM, LM' 'CB, CM' 'RWB, RW, RB'
 'ST, RW, RM' 'LW, RW, CM' 'LM, RM, CAM' 'LB, RB' 'RWB, RM, RB'
 'LM, RB, LB' 'LW, LM, ST' 'ST, RM, LM' 'CAM, CM, LM' 'CF, CM'
 'LW, ST, RW' 'ST, CAM, CF' 'LB, CB, LM' 'CM, CDM, LM' 'RM, RWB'
 'LB, LM, RB' 'RB, LB, CB' 'CM, CDM, RB' 'LB, CM' 'CF, CAM, LW' 'RM, LWB'
 'CF, ST, LM' 'LB, RB, CB' 'LW, CF, ST' 'RM, ST, CAM' 'LW, RW, ST'
 'ST, LW, LM' 'CM, LW' 'CDM, CM, LB' 'CM, RM, CAM' 'ST, CF, CAM'
 'CM, LM, CAM' 'RWB' 'LM, ST, RM' 'CAM, RM, CM' 'CAM, LM, CM' 'RW, LW, ST'
 'CAM, RM, LM' 'CF, ST, LW' 'LWB, LB, LM' 'RM, CM, CAM' 'LB, LM, CAM'
 'CAM, CDM' 'RW, RB, RM' 'RM, ST, RW' 'CM, CAM, LW' 'CF, ST, RW'
 'LM, RM, RB' 'LM, RM, CM' 'CB, RB, RM' 'RB, CDM' 'RM, ST, LM'
 'LB, LWB, CB' 'CDM, LB' 'LM, RM, ST' 'RWB, RB, LWB' 'ST, LM, CAM'
 'ST, RM, CAM' 'RB, RWB, RM' 'CF, LM, CAM' 'CAM, CF, RW' 'RB, RM, LB'
 'CDM, RWB' 'CM, RW, CAM' 'ST, CF, LM' 'RM, LM, RWB' 'RB, LB, RM'
 'LM, LW, LB' 'RM, LM, ST' 'CAM, LM' 'ST, LM, LW' 'LW, RW, RM' 'CF, LW'
 'LB, CM, RB' 'RB, CB, CDM' 'CB, RB, LB' 'CAM, RW, RM' 'LWB, LM'
 'LW, CF, LM' 'CAM, CF, CM' 'LWB, CB' 'CM, CDM, LW' 'LM, CM, LB' 'CM, RM'
 'RW, LW, CF' 'CM, CDM, CB' 'LM, RM, RW' 'RM, RW, LM' 'RM, CAM, LM'
 'LWB, RM, LB' 'RM, LB, RB' 'CM, CF, RM' 'RM, RB, LB' 'ST, LM, RW'
 'CAM, ST, LW' 'CF, LW, ST' 'LM, LW, CAM' 'RM, RW, CF' 'LW, LM, CF'
 'CM, RW, LW' 'LM, CM, CAM' 'CAM, RW, ST' 'CM, CAM, CF' 'RW, LWB, LW'
 'CB, RB, CDM' 'RW, RM, LW' 'LW, ST, LM' 'RWB, RW' 'ST, CAM, LM' 'CM, CB'
 'RM, RW, CM' 'LWB, CM' 'RM, LM, LB' 'RM, CAM, ST' 'CDM, RM, RB'
 'LM, LB, RB' 'LB, RB, RWB' 'RM, RWB, CAM' 'CAM, LM, CF' 'LM, CAM, CM'
 'CF, CAM, RW' 'CDM, CM, RM' 'CF, CAM, CM' 'ST, RM, LW' 'CB, CDM, CM'
 'RB, RW, LB' 'ST, RW, CAM' 'CM, LB' 'LW, RM, RW' 'CM, RM, RW'
 'RM, CF, LM' 'CF, LM, RM' 'CAM, ST, RM' 'RW, CF' 'CM, CAM, ST'
 'CAM, CDM, CM' 'RM, RW, LW' 'CAM, LM, LB' 'CAM, RW, LW' 'CDM, CAM'
 'LWB, LM, LB' 'RW, LB' 'LW, CAM, CF' 'RB, RWB, CB' 'LM, CF, RM'
 'RB, LB, RWB' 'RM, LW' 'CAM, LM, ST' 'LW, LM, LB' 'LB, RB, RM' 'CM, LWB'

In [27]:
#Columns to clean:
    #'Contract'
    #'Height'
    #'Weight'
    #'Joined'
    #'Value'
    #'Wage'
    #'Release Clause'
    #'W/F'
    #'SM'
    #'IR'

In [28]:
#Finding records where in 'Contract' is value 'Jun 30, 2021 On Loan'
df.loc[df['Contract'] == 'Jun 30, 2021 On Loan']

,Name,Nationality,Age,OVA,POT,Club,Contract,Positions,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
ID,,,,,,,,,,,,,,,,,,,,,
173731,Gareth Bale,Wales,30,83,83,Tottenham Hotspur,"Jun 30, 2021 On Loan",RW,185cm,82kg,...,Medium,Medium,4 ★,88,84,82,80,58,73,282
193105,Alphonse Areola,France,27,82,86,Fulham,"Jun 30, 2021 On Loan",GK,195cm,94kg,...,Medium,Medium,2 ★,85,79,80,84,55,78,94
200888,Danilo Luís Hélio Pereira,Portugal,28,82,82,Paris Saint-Germain,"Jun 30, 2021 On Loan","CDM, CM",188cm,83kg,...,Medium,High,3 ★,66,63,72,73,80,85,285
216409,Matteo Politano,Italy,26,81,81,Napoli,"Jun 30, 2021 On Loan","RM, RW, ST",171cm,67kg,...,High,Medium,2 ★,83,77,78,84,42,55,93
223959,Lucas Torreira,Uruguay,24,81,85,Atlético Madrid,"Jun 30, 2021 On Loan","CDM, CM",166cm,60kg,...,Medium,High,2 ★,74,67,75,79,79,74,194
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259201,Danny Finlayson,Northern Ireland,19,53,69,St. Mirren,"Jun 30, 2021 On Loan",RB,191cm,83kg,...,Medium,Medium,1 ★,67,34,41,51,50,64,0
258883,Bradley Webb,England,19,53,69,Newport County,"Jun 30, 2021 On Loan","CB, LB",188cm,79kg,...,Medium,Medium,1 ★,67,26,39,42,52,63,0
253227,Ethan Walker,England,17,53,71,Carlisle United,"Jun 30, 2021 On Loan",ST,184cm,75kg,...,High,Medium,1 ★,56,58,41,51,21,48,0
251420,Tyrese Fornah,England,20,52,66,Plymouth Argyle,"Jun 30, 2021 On Loan",CM,185cm,72kg,...,Medium,Medium,1 ★,67,40,53,48,42,66,0
236818,Arthur Read,England,20,51,63,Stevenage,"Jun 30, 2021 On Loan","CM, RW, LW",178cm,64kg,...,Medium,Medium,1 ★,57,45,52,59,38,48,0

In [29]:
#Finding records where in 'Contract' is value 'Free'
df.loc[df['Contract'] == 'Free']

,Name,Nationality,Age,OVA,POT,Club,Contract,Positions,Height,Weight,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
ID,,,,,,,,,,,,,,,,,,,,,
230347,Welington Kauê Dano Nascimento,Brazil,20,81,81,No Club,Free,"LB, LM",178cm,69kg,...,Medium,Medium,1 ★,79,54,76,78,75,74,172
230225,Juan Everton Mestres de Mesquita,Brazil,24,81,81,No Club,Free,"CB, CDM",181cm,82kg,...,High,Medium,1 ★,71,61,57,62,82,80,75
245299,Jaime Nicolás Frendado,Uruguay,36,80,80,No Club,Free,"CB, CDM",181cm,82kg,...,High,Medium,1 ★,71,61,57,62,82,75,11
245294,Jorge Ezequiel Serendero,Uruguay,32,80,80,No Club,Free,GK,190cm,85kg,...,Medium,Medium,1 ★,78,81,77,77,42,80,18
245308,Mauro Evidio Nérez,Uruguay,32,80,80,No Club,Free,"LB, LM",178cm,69kg,...,Medium,Medium,1 ★,79,54,75,78,76,74,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247059,Ali Al Hidhani,United Arab Emirates,22,56,64,No Club,Free,RB,172cm,67kg,...,Medium,Medium,1 ★,73,33,45,55,51,55,0
251734,Anudaan Sanghu,India,20,56,56,No Club,Free,"RM, CM",168cm,62kg,...,Medium,Low,1 ★,79,42,50,59,29,49,0
251738,Madanapal Chada,India,27,55,55,No Club,Free,ST,178cm,77kg,...,High,Medium,1 ★,67,52,47,61,32,57,0
251741,Eelamynthan Suresh,India,28,55,55,No Club,Free,"RM, CAM, RB",175cm,73kg,...,High,Medium,1 ★,73,49,51,54,41,70,0
251737,Jagatjiva Mangat,India,26,53,54,No Club,Free,LM,171cm,65kg,...,Medium,Medium,1 ★,68,41,45,58,22,41,0

In [30]:
#Splitting column Contract with delimiter ' ~ ', and creating 2 columns 'Contract Start Year' and 'Contract End Year'
df[['Contract Start Year', 'Contract End Year']] = df['Contract'].str.split(' ~ ', expand=True)

In [31]:
#Checking results
df

,Name,Nationality,Age,OVA,POT,Club,Contract,Positions,Height,Weight,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Contract Start Year,Contract End Year
ID,,,,,,,,,,,,,,,,,,,,,
158023,Lionel Messi,Argentina,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,...,5 ★,85,92,91,95,38,65,771,2004,2021
20801,C. Ronaldo dos Santos Aveiro,Portugal,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187cm,83kg,...,5 ★,89,93,81,89,35,77,562,2018,2022
200389,Jan Oblak,Slovenia,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188cm,87kg,...,3 ★,87,92,78,90,52,90,150,2014,2023
192985,Kevin De Bruyne,Belgium,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,...,4 ★,76,86,93,88,64,78,207,2015,2023
190871,Neymar da Silva Santos Jr.,Brazil,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,...,5 ★,91,85,86,94,36,59,595,2017,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247223,Ao Xia,China PR,21,47,55,Wuhan Zall,2018 ~ 2022,CB,178cm,66kg,...,1 ★,64,28,26,38,48,51,0,2018,2022
258760,Ben Hough,England,17,47,67,Oldham Athletic,2020 ~ 2021,CM,175cm,65kg,...,1 ★,64,40,48,49,35,45,0,2020,2021
252757,Ronan McKinley,England,18,47,65,Derry City,2019 ~ 2020,CM,179cm,74kg,...,1 ★,63,39,44,46,40,53,0,2019,2020
243790,Zhen'ao Wang,China PR,20,47,57,Dalian YiFang FC,2020 ~ 2022,RW,175cm,69kg,...,1 ★,58,49,41,49,30,44,0,2020,2022
252520,Xiao Zhou,China PR,21,47,57,Dalian YiFang FC,2019 ~ 2023,"CB, LB",188cm,75kg,...,1 ★,62,22,39,42,45,55,0,2019,2023

In [32]:
#Creating the new column 'On Loan' and assign True or False according column 'Contract'
df['On Loan'] = df['Contract'].str.contains('On Loan')

In [33]:
#Where in 'On Loan' is True, replacing in 'Contract Start Year' value ' On Loan' with ''
#df.loc[df['On Loan'] == True, 'Contract Start Year'] = df.loc[df['On Loan'] == True, 'Contract Start Year'].str.replace(' On Loan', '')

In [34]:
# Showing only the four columns of interest
# Assigning -1 to the column 'Contract Start Year' where the column 'Loan Date End' is not equal to 'Not a loan'
df.loc[df['Loan Date End'] != 'Not a loan', 'Contract Start Year'] = -1
df.loc[df['Loan Date End'] != 'Not a loan', ['Contract', 'Loan Date End', 'On Loan', 'Contract End Year', 'Contract Start Year']]
# Dropping the column 'Contract' from the dataframe
#df = df.drop('Contract', axis=1)

,Contract,Loan Date End,On Loan,Contract End Year,Contract Start Year
ID,,,,,
173731,"Jun 30, 2021 On Loan","Jun 30, 2021",True,None,-1
193105,"Jun 30, 2021 On Loan","Jun 30, 2021",True,None,-1
200888,"Jun 30, 2021 On Loan","Jun 30, 2021",True,None,-1
216409,"Jun 30, 2021 On Loan","Jun 30, 2021",True,None,-1
223959,"Jun 30, 2021 On Loan","Jun 30, 2021",True,None,-1
...,...,...,...,...,...
242601,"Aug 31, 2021 On Loan","Aug 31, 2021",True,None,-1
236818,"Jun 30, 2021 On Loan","Jun 30, 2021",True,None,-1
240392,"Dec 31, 2020 On Loan","Dec 31, 2020",True,None,-1
252516,"Dec 31, 2020 On Loan","Dec 31, 2020",True,None,-1
232888,"Dec 31, 2020 On Loan","Dec 31, 2020",True,None,-1

In [35]:
df['Contract Start Year'].unique()

array(['2004', '2018', '2014', '2015', '2017', '2016', '2013', '2011',
       '2009', '2005', '2010', '2012', '2019', '2020', '2008', '2007', -1,
       'Free', '2002', '2006', '2003', '1998'], dtype=object)

In [36]:
df[df['Contract'] == 'Free']

,Name,Nationality,Age,OVA,POT,Club,Contract,Positions,Height,Weight,...,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Contract Start Year,Contract End Year,On Loan
ID,,,,,,,,,,,,,,,,,,,,,
230347,Welington Kauê Dano Nascimento,Brazil,20,81,81,No Club,Free,"LB, LM",178cm,69kg,...,79,54,76,78,75,74,172,Free,None,False
230225,Juan Everton Mestres de Mesquita,Brazil,24,81,81,No Club,Free,"CB, CDM",181cm,82kg,...,71,61,57,62,82,80,75,Free,None,False
245299,Jaime Nicolás Frendado,Uruguay,36,80,80,No Club,Free,"CB, CDM",181cm,82kg,...,71,61,57,62,82,75,11,Free,None,False
245294,Jorge Ezequiel Serendero,Uruguay,32,80,80,No Club,Free,GK,190cm,85kg,...,78,81,77,77,42,80,18,Free,None,False
245308,Mauro Evidio Nérez,Uruguay,32,80,80,No Club,Free,"LB, LM",178cm,69kg,...,79,54,75,78,76,74,17,Free,None,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247059,Ali Al Hidhani,United Arab Emirates,22,56,64,No Club,Free,RB,172cm,67kg,...,73,33,45,55,51,55,0,Free,None,False
251734,Anudaan Sanghu,India,20,56,56,No Club,Free,"RM, CM",168cm,62kg,...,79,42,50,59,29,49,0,Free,None,False
251738,Madanapal Chada,India,27,55,55,No Club,Free,ST,178cm,77kg,...,67,52,47,61,32,57,0,Free,None,False
251741,Eelamynthan Suresh,India,28,55,55,No Club,Free,"RM, CAM, RB",175cm,73kg,...,73,49,51,54,41,70,0,Free,None,False
251737,Jagatjiva Mangat,India,26,53,54,No Club,Free,LM,171cm,65kg,...,68,41,45,58,22,41,0,Free,None,False

In [37]:
# Create a new boolean column 'Is_Free'
df['Is_Free'] = (df['Contract Start Year'] == 'Free')

# Set 'Contract Start Year' to None where 'Is_Free' is 1
df.loc[df['Is_Free'] == 1, 'Contract Start Year'] = None

In [38]:
df[df['Is_Free'] == 1]

,Name,Nationality,Age,OVA,POT,Club,Contract,Positions,Height,Weight,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract Start Year,Contract End Year,On Loan,Is_Free
ID,,,,,,,,,,,,,,,,,,,,,
230347,Welington Kauê Dano Nascimento,Brazil,20,81,81,No Club,Free,"LB, LM",178cm,69kg,...,54,76,78,75,74,172,None,None,False,True
230225,Juan Everton Mestres de Mesquita,Brazil,24,81,81,No Club,Free,"CB, CDM",181cm,82kg,...,61,57,62,82,80,75,None,None,False,True
245299,Jaime Nicolás Frendado,Uruguay,36,80,80,No Club,Free,"CB, CDM",181cm,82kg,...,61,57,62,82,75,11,None,None,False,True
245294,Jorge Ezequiel Serendero,Uruguay,32,80,80,No Club,Free,GK,190cm,85kg,...,81,77,77,42,80,18,None,None,False,True
245308,Mauro Evidio Nérez,Uruguay,32,80,80,No Club,Free,"LB, LM",178cm,69kg,...,54,75,78,76,74,17,None,None,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247059,Ali Al Hidhani,United Arab Emirates,22,56,64,No Club,Free,RB,172cm,67kg,...,33,45,55,51,55,0,None,None,False,True
251734,Anudaan Sanghu,India,20,56,56,No Club,Free,"RM, CM",168cm,62kg,...,42,50,59,29,49,0,None,None,False,True
251738,Madanapal Chada,India,27,55,55,No Club,Free,ST,178cm,77kg,...,52,47,61,32,57,0,None,None,False,True
251741,Eelamynthan Suresh,India,28,55,55,No Club,Free,"RM, CAM, RB",175cm,73kg,...,49,51,54,41,70,0,None,None,False,True
251737,Jagatjiva Mangat,India,26,53,54,No Club,Free,LM,171cm,65kg,...,41,45,58,22,41,0,None,None,False,True

In [39]:
df[df['On Loan']==True]

,Name,Nationality,Age,OVA,POT,Club,Contract,Positions,Height,Weight,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract Start Year,Contract End Year,On Loan,Is_Free
ID,,,,,,,,,,,,,,,,,,,,,
173731,Gareth Bale,Wales,30,83,83,Tottenham Hotspur,"Jun 30, 2021 On Loan",RW,185cm,82kg,...,84,82,80,58,73,282,-1,None,True,False
193105,Alphonse Areola,France,27,82,86,Fulham,"Jun 30, 2021 On Loan",GK,195cm,94kg,...,79,80,84,55,78,94,-1,None,True,False
200888,Danilo Luís Hélio Pereira,Portugal,28,82,82,Paris Saint-Germain,"Jun 30, 2021 On Loan","CDM, CM",188cm,83kg,...,63,72,73,80,85,285,-1,None,True,False
216409,Matteo Politano,Italy,26,81,81,Napoli,"Jun 30, 2021 On Loan","RM, RW, ST",171cm,67kg,...,77,78,84,42,55,93,-1,None,True,False
223959,Lucas Torreira,Uruguay,24,81,85,Atlético Madrid,"Jun 30, 2021 On Loan","CDM, CM",166cm,60kg,...,67,75,79,79,74,194,-1,None,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242601,Moudi Najjar,Australia,20,52,65,Macarthur FC,"Aug 31, 2021 On Loan",ST,182cm,72kg,...,51,39,53,21,52,0,-1,None,True,False
236818,Arthur Read,England,20,51,63,Stevenage,"Jun 30, 2021 On Loan","CM, RW, LW",178cm,64kg,...,45,52,59,38,48,0,-1,None,True,False
240392,Yubiao Deng,China PR,23,51,60,Shijiazhuang Ever Bright F.C.,"Dec 31, 2020 On Loan",CM,181cm,65kg,...,42,52,54,47,52,0,-1,None,True,False
252516,Pu Chen,China PR,23,51,60,Shijiazhuang Ever Bright F.C.,"Dec 31, 2020 On Loan","CAM, LM",177cm,68kg,...,41,55,49,34,47,0,-1,None,True,False
232888,Zhechao Chen,China PR,25,51,56,Guangzhou R&F FC,"Dec 31, 2020 On Loan","CM, LM, LB",177cm,70kg,...,35,49,50,59,58,0,-1,None,True,False

In [40]:
df['Contract Start Year'].unique()

array(['2004', '2018', '2014', '2015', '2017', '2016', '2013', '2011',
       '2009', '2005', '2010', '2012', '2019', '2020', '2008', '2007', -1,
       None, '2002', '2006', '2003', '1998'], dtype=object)

In [41]:
df['Contract End Year'].unique()

array(['2021', '2022', '2023', '2024', '2025', '2026', None, '2028',
       '2020', '2027'], dtype=object)

In [42]:
df['On Loan'].unique()

array([False,  True])

In [43]:
df['Is_Free'].unique()

array([False,  True])

In [44]:
#Replace None with -1 in 'Contract Start Year' and 'Contract End Year'
#Contract Is_Free == True or On loan == True
df[['Contract Start Year', 'Contract End Year']] = df[['Contract Start Year', 'Contract End Year']].fillna(-1)

In [45]:
#Checking result
df[df['Is_Free'] == True]

,Name,Nationality,Age,OVA,POT,Club,Contract,Positions,Height,Weight,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract Start Year,Contract End Year,On Loan,Is_Free
ID,,,,,,,,,,,,,,,,,,,,,
230347,Welington Kauê Dano Nascimento,Brazil,20,81,81,No Club,Free,"LB, LM",178cm,69kg,...,54,76,78,75,74,172,-1,-1,False,True
230225,Juan Everton Mestres de Mesquita,Brazil,24,81,81,No Club,Free,"CB, CDM",181cm,82kg,...,61,57,62,82,80,75,-1,-1,False,True
245299,Jaime Nicolás Frendado,Uruguay,36,80,80,No Club,Free,"CB, CDM",181cm,82kg,...,61,57,62,82,75,11,-1,-1,False,True
245294,Jorge Ezequiel Serendero,Uruguay,32,80,80,No Club,Free,GK,190cm,85kg,...,81,77,77,42,80,18,-1,-1,False,True
245308,Mauro Evidio Nérez,Uruguay,32,80,80,No Club,Free,"LB, LM",178cm,69kg,...,54,75,78,76,74,17,-1,-1,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247059,Ali Al Hidhani,United Arab Emirates,22,56,64,No Club,Free,RB,172cm,67kg,...,33,45,55,51,55,0,-1,-1,False,True
251734,Anudaan Sanghu,India,20,56,56,No Club,Free,"RM, CM",168cm,62kg,...,42,50,59,29,49,0,-1,-1,False,True
251738,Madanapal Chada,India,27,55,55,No Club,Free,ST,178cm,77kg,...,52,47,61,32,57,0,-1,-1,False,True
251741,Eelamynthan Suresh,India,28,55,55,No Club,Free,"RM, CAM, RB",175cm,73kg,...,49,51,54,41,70,0,-1,-1,False,True
251737,Jagatjiva Mangat,India,26,53,54,No Club,Free,LM,171cm,65kg,...,41,45,58,22,41,0,-1,-1,False,True

In [46]:
#Checking result
df[df['On Loan']==True]

,Name,Nationality,Age,OVA,POT,Club,Contract,Positions,Height,Weight,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract Start Year,Contract End Year,On Loan,Is_Free
ID,,,,,,,,,,,,,,,,,,,,,
173731,Gareth Bale,Wales,30,83,83,Tottenham Hotspur,"Jun 30, 2021 On Loan",RW,185cm,82kg,...,84,82,80,58,73,282,-1,-1,True,False
193105,Alphonse Areola,France,27,82,86,Fulham,"Jun 30, 2021 On Loan",GK,195cm,94kg,...,79,80,84,55,78,94,-1,-1,True,False
200888,Danilo Luís Hélio Pereira,Portugal,28,82,82,Paris Saint-Germain,"Jun 30, 2021 On Loan","CDM, CM",188cm,83kg,...,63,72,73,80,85,285,-1,-1,True,False
216409,Matteo Politano,Italy,26,81,81,Napoli,"Jun 30, 2021 On Loan","RM, RW, ST",171cm,67kg,...,77,78,84,42,55,93,-1,-1,True,False
223959,Lucas Torreira,Uruguay,24,81,85,Atlético Madrid,"Jun 30, 2021 On Loan","CDM, CM",166cm,60kg,...,67,75,79,79,74,194,-1,-1,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242601,Moudi Najjar,Australia,20,52,65,Macarthur FC,"Aug 31, 2021 On Loan",ST,182cm,72kg,...,51,39,53,21,52,0,-1,-1,True,False
236818,Arthur Read,England,20,51,63,Stevenage,"Jun 30, 2021 On Loan","CM, RW, LW",178cm,64kg,...,45,52,59,38,48,0,-1,-1,True,False
240392,Yubiao Deng,China PR,23,51,60,Shijiazhuang Ever Bright F.C.,"Dec 31, 2020 On Loan",CM,181cm,65kg,...,42,52,54,47,52,0,-1,-1,True,False
252516,Pu Chen,China PR,23,51,60,Shijiazhuang Ever Bright F.C.,"Dec 31, 2020 On Loan","CAM, LM",177cm,68kg,...,41,55,49,34,47,0,-1,-1,True,False
232888,Zhechao Chen,China PR,25,51,56,Guangzhou R&F FC,"Dec 31, 2020 On Loan","CM, LM, LB",177cm,70kg,...,35,49,50,59,58,0,-1,-1,True,False

In [47]:
#Drop original 'Contract' column
df = df.drop(['Contract'], axis=1)

In [48]:
#Rename 'On Loan' and 'Is_Free' columns
df = df.rename(columns={'On Loan': 'Contract is on loan', 'Is_Free': 'Contract is free'})

In [49]:
#Checking results
df

,Name,Nationality,Age,OVA,POT,Club,Positions,Height,Weight,Preferred Foot,...,SHO,PAS,DRI,DEF,PHY,Hits,Contract Start Year,Contract End Year,Contract is on loan,Contract is free
ID,,,,,,,,,,,,,,,,,,,,,
158023,Lionel Messi,Argentina,33,93,93,FC Barcelona,"RW, ST, CF",170cm,72kg,Left,...,92,91,95,38,65,771,2004,2021,False,False
20801,C. Ronaldo dos Santos Aveiro,Portugal,35,92,92,Juventus,"ST, LW",187cm,83kg,Right,...,93,81,89,35,77,562,2018,2022,False,False
200389,Jan Oblak,Slovenia,27,91,93,Atlético Madrid,GK,188cm,87kg,Right,...,92,78,90,52,90,150,2014,2023,False,False
192985,Kevin De Bruyne,Belgium,29,91,91,Manchester City,"CAM, CM",181cm,70kg,Right,...,86,93,88,64,78,207,2015,2023,False,False
190871,Neymar da Silva Santos Jr.,Brazil,28,91,91,Paris Saint-Germain,"LW, CAM",175cm,68kg,Right,...,85,86,94,36,59,595,2017,2022,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247223,Ao Xia,China PR,21,47,55,Wuhan Zall,CB,178cm,66kg,Right,...,28,26,38,48,51,0,2018,2022,False,False
258760,Ben Hough,England,17,47,67,Oldham Athletic,CM,175cm,65kg,Right,...,40,48,49,35,45,0,2020,2021,False,False
252757,Ronan McKinley,England,18,47,65,Derry City,CM,179cm,74kg,Right,...,39,44,46,40,53,0,2019,2020,False,False
243790,Zhen'ao Wang,China PR,20,47,57,Dalian YiFang FC,RW,175cm,69kg,Right,...,49,41,49,30,44,0,2020,2022,False,False
252520,Xiao Zhou,China PR,21,47,57,Dalian YiFang FC,"CB, LB",188cm,75kg,Left,...,22,39,42,45,55,0,2019,2023,False,False

In [50]:
#Converiting whole column to cm
def convert_height(height):
    if 'cm' in height:
        return float(height.replace('cm', ''))
    elif '\'' in height:
        feet, inches = height.replace('"', '').split('\'')
        return float(feet) * 30.48 + float(inches) * 2.54
    else:
        return None

df['Height'] = df['Height'].apply(convert_height)
df[['Height']]

        Height
ID
158023   170.0
20801    187.0
200389   188.0
192985   181.0
190871   175.0
...        ...
247223   178.0
258760   175.0
252757   179.0
243790   175.0
252520   188.0

[18979 rows x 1 columns]

In [51]:
#Checking results
df['Height'].unique()

array([170.  , 187.  , 188.  , 181.  , 175.  , 184.  , 191.  , 178.  ,
       193.  , 185.  , 199.  , 173.  , 168.  , 176.  , 177.  , 183.  ,
       180.  , 189.  , 179.  , 195.  , 172.  , 182.  , 186.  , 192.  ,
       165.  , 194.  , 167.  , 196.  , 163.  , 190.  , 174.  , 169.  ,
       171.  , 197.  , 200.  , 166.  , 187.96, 164.  , 198.  , 190.5 ,
       195.58, 180.34, 193.04, 185.42, 182.88, 177.8 , 175.26, 167.64,
       170.18, 162.56, 201.  , 158.  , 162.  , 161.  , 160.  , 203.  ,
       157.  , 156.  , 202.  , 159.  , 206.  , 155.  ])

In [52]:
#Converiting whole column to kg
def convert_weight(weight):
    if 'kg' in weight:
        return float(weight.replace('kg', ''))
    elif 'lbs' in weight:
        return float(weight.replace('lbs', '')) * 0.453592
    else:
        return None

df['Weight'] = df['Weight'].apply(convert_weight)
df[['Weight']]

        Weight
ID
158023    72.0
20801     83.0
200389    87.0
192985    70.0
190871    68.0
...        ...
247223    66.0
258760    65.0
252757    74.0
243790    69.0
252520    75.0

[18979 rows x 1 columns]

In [53]:
#Checking results
df['Weight'].unique()

array([ 72.      ,  83.      ,  87.      ,  70.      ,  68.      ,
        80.      ,  71.      ,  91.      ,  73.      ,  85.      ,
        92.      ,  69.      ,  84.      ,  96.      ,  81.      ,
        82.      ,  75.      ,  86.      ,  89.      ,  74.      ,
        76.      ,  64.      ,  78.      ,  90.      ,  66.      ,
        60.      ,  94.      ,  79.      ,  67.      ,  65.      ,
        59.      ,  61.      ,  93.      ,  88.      ,  97.      ,
        77.      ,  62.      ,  63.      ,  95.      , 100.      ,
        58.      ,  83.007336,  81.192968,  78.017824,  88.904032,
        79.832192,  83.91452 ,  77.11064 ,  92.079176,  76.203456,
        73.028312,  66.224432,  58.96696 ,  86.18248 ,  78.925008,
        67.131616,  74.84268 ,  72.121128,  87.089664,  82.100152,
        63.049288,  69.853168,  71.213944,  73.935496,  98.      ,
       103.      ,  99.      , 102.      ,  56.      , 101.      ,
        57.      ,  55.      , 104.      , 107.      , 110.      ,
        53.      ,  50.      ,  54.      ,  52.      ])

In [54]:
#Stripping ★ symbol from 'W/F', 'SM', and 'IR' columns
df['W/F'] = df['W/F'].str.strip("★").astype(int)
df['SM'] = df['SM'].str.strip("★").astype(int)
df['IR'] = df['IR'].str.strip("★").astype(int)

#Renaming the columns with a star symbol
df = df.rename(columns={'W/F': 'W/F★', 'SM': 'SM★', 'IR': 'IR★'})

In [55]:
#Checking results
df[['W/F★', 'SM★', 'IR★']]

        W/F★  SM★  IR★
ID
158023     4    4    5
20801      4    5    5
200389     3    1    3
192985     5    4    4
190871     5    5    5
...      ...  ...  ...
247223     2    2    1
258760     2    2    1
252757     2    2    1
243790     3    2    1
252520     3    2    1

[18979 rows x 3 columns]

In [56]:
# Converting the column 'Joined' to date
df['Joined'] = pd.to_datetime(df['Joined'])
#Checking results
df[['Joined']]

           Joined
ID
158023 2004-07-01
20801  2018-07-10
200389 2014-07-16
192985 2015-08-30
190871 2017-08-03
...           ...
247223 2018-07-13
258760 2020-08-01
252757 2019-03-08
243790 2020-09-22
252520 2019-07-29

[18979 rows x 1 columns]

In [57]:
df['Joined'].unique()

<DatetimeArray>
['2004-07-01 00:00:00', '2018-07-10 00:00:00', '2014-07-16 00:00:00',
 '2015-08-30 00:00:00', '2017-08-03 00:00:00', '2014-07-01 00:00:00',
 '2017-07-01 00:00:00', '2018-07-19 00:00:00', '2018-07-01 00:00:00',
 '2018-01-01 00:00:00',
 ...
 '2019-10-12 00:00:00', '2019-03-23 00:00:00', '2020-03-25 00:00:00',
 '2019-05-02 00:00:00', '2019-06-08 00:00:00', '2019-12-19 00:00:00',
 '2020-05-02 00:00:00', '2018-09-22 00:00:00', '2015-02-28 00:00:00',
 '2018-03-06 00:00:00']
Length: 1869, dtype: datetime64[ns]

In [58]:
#Showing columns to clean
df[['Value', 'Wage', 'Release Clause']]

          Value   Wage Release Clause
ID
158023  €103.5M  €560K        €138.4M
20801      €63M  €220K         €75.9M
200389    €120M  €125K        €159.4M
192985    €129M  €370K          €161M
190871    €132M  €270K        €166.5M
...         ...    ...            ...
247223    €100K    €1K           €70K
258760    €130K   €500          €165K
252757    €120K   €500          €131K
243790    €100K    €2K           €88K
252520    €100K    €1K           €79K

[18979 rows x 3 columns]

In [59]:
#Changing 'Wage', 'Value', 'Release Clause' to int type, removing sigh '€', replacing 'K' and 'M', with zeroes
columnsKM=['Wage', 'Value', 'Release Clause']

for c in columnsKM:
    df[c] = df[c].str.strip('€')
    d = {'M': '*1000000', 'K': '*1000'}
    s_convert = df[c].replace(d, regex=True).map(pd.eval)
    df[c] = s_convert.astype(int)

In [60]:
#Showing results
df[['Value', 'Wage', 'Release Clause']]

            Value    Wage  Release Clause
ID
158023  103500000  560000       138400000
20801    63000000  220000        75900000
200389  120000000  125000       159400000
192985  129000000  370000       161000000
190871  132000000  270000       166500000
...           ...     ...             ...
247223     100000    1000           70000
258760     130000     500          165000
252757     120000     500          131000
243790     100000    2000           88000
252520     100000    1000           79000

[18979 rows x 3 columns]

In [61]:
#Getting names of columns
df.columns

Index(['Name', 'Nationality', 'Age', 'OVA', 'POT', 'Club', 'Positions',
       'Height', 'Weight', 'Preferred Foot', 'BOV', 'Best Position', 'Joined',
       'Loan Date End', 'Value', 'Wage', 'Release Clause', 'Attacking',
       'Crossing', 'Finishing', 'Heading Accuracy', 'Short Passing', 'Volleys',
       'Skill', 'Dribbling', 'Curve', 'FK Accuracy', 'Long Passing',
       'Ball Control', 'Movement', 'Acceleration', 'Sprint Speed', 'Agility',
       'Reactions', 'Balance', 'Power', 'Shot Power', 'Jumping', 'Stamina',
       'Strength', 'Long Shots', 'Mentality', 'Aggression', 'Interceptions',
       'Positioning', 'Vision', 'Penalties', 'Composure', 'Defending',
       'Marking', 'Standing Tackle', 'Sliding Tackle', 'Goalkeeping',
       'GK Diving', 'GK Handling', 'GK Kicking', 'GK Positioning',
       'GK Reflexes', 'Total Stats', 'Base Stats', 'W/F★', 'SM★', 'A/W', 'D/W',
       'IR★', 'PAC', 'SHO', 'PAS', 'DRI', 'DEF', 'PHY', 'Hits',
       'Contract Start Year', 'Contract End Year', 'Contract is on loan',
       'Contract is free'],
      dtype='object')

In [62]:
#Define the new order of columns
new_column_order = ['Name', 'Nationality', 'Age', 'OVA', 'POT', 'Club', 'Joined', 'Contract Start Year', 'Contract End Year', 'Contract is on loan', 'Loan Date End', 'Contract is free']

#Other columns in the DataFrame
other_columns = [col for col in df.columns if col not in new_column_order]

#Reorder the columns
df = df[new_column_order + other_columns]

In [63]:
#Reordered columns
df.columns

Index(['Name', 'Nationality', 'Age', 'OVA', 'POT', 'Club', 'Joined',
       'Contract Start Year', 'Contract End Year', 'Contract is on loan',
       'Loan Date End', 'Contract is free', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Value', 'Wage',
       'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F★', 'SM★', 'A/W', 'D/W', 'IR★', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [64]:
#Showing sample of df(first 10 record) all columns
pd.set_option('display.max_columns', None)
df.head(10)

,Name,Nationality,Age,OVA,POT,Club,Joined,Contract Start Year,Contract End Year,Contract is on loan,Loan Date End,Contract is free,Positions,Height,Weight,Preferred Foot,BOV,Best Position,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F★,SM★,A/W,D/W,IR★,PAC,SHO,PAS,DRI,DEF,PHY,Hits
ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
158023,Lionel Messi,Argentina,33,93,93,FC Barcelona,2004-07-01,2004,2021,False,Not a loan,False,"RW, ST, CF",170.0,72.0,Left,93,RW,103500000,560000,138400000,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4,4,Medium,Low,5,85,92,91,95,38,65,771
20801,C. Ronaldo dos Santos Aveiro,Portugal,35,92,92,Juventus,2018-07-10,2018,2022,False,Not a loan,False,"ST, LW",187.0,83.0,Right,92,ST,63000000,220000,75900000,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4,5,High,Low,5,89,93,81,89,35,77,562
200389,Jan Oblak,Slovenia,27,91,93,Atlético Madrid,2014-07-16,2014,2023,False,Not a loan,False,GK,188.0,87.0,Right,91,GK,120000000,125000,159400000,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3,1,Medium,Medium,3,87,92,78,90,52,90,150
192985,Kevin De Bruyne,Belgium,29,91,91,Manchester City,2015-08-30,2015,2023,False,Not a loan,False,"CAM, CM",181.0,70.0,Right,91,CAM,129000000,370000,161000000,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5,4,High,High,4,76,86,93,88,64,78,207
190871,Neymar da Silva Santos Jr.,Brazil,28,91,91,Paris Saint-Germain,2017-08-03,2017,2022,False,Not a loan,False,"LW, CAM",175.0,68.0,Right,91,LW,132000000,270000,166500000,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5,5,High,Medium,5,91,85,86,94,36,59,595
188545,Robert Lewandowski,Poland,31,91,91,FC Bayern München,2014-07-01,2014,2023,False,Not a loan,False,ST,184.0,80.0,Right,91,ST,111000000,240000,132000000,423,71,94,85,84,89,407,85,79,85,70,88,407,77,78,77,93,82,420,89,84,76,86,85,391,81,49,94,79,88,88,96,35,42,19,51,15,6,12,8,10,2195,457,4,4,High,Medium,4,78,91,78,85,43,82,248
209331,Mohamed Salah,Egypt,28,90,90,Liverpool,2017-07-01,2017,2023,False,Not a loan,False,RW,175.0,71.0,Left,90,RW,120500000,250000,144300000,392,79,91,59,84,79,406,90,83,69,75,89,460,94,92,91,92,91,393,80,69,85,75,84,376,63,55,91,84,83,90,122,38,43,41,62,14,14,9,11,14,2211,470,3,4,High,Medium,3,93,86,81,90,45,75,246
212831,Alisson Ramses Becker,Brazil,27,90,91,Liverpool,2018-07-19,2018,2024,False,Not a loan,False,GK,191.0,91.0,Right,90,GK,102000000,160000,120300000,114,17,13,19,45,20,138,27,19,18,44,30,268,56,47,40,88,37,240,64,52,32,78,14,140,27,11,13,66,23,65,50,15,19,16,439,86,88,85,91,89,1389,490,3,1,Medium,Medium,3,86,88,85,89,51,91,120
231747,Kylian Mbappé,France,21,90,95,Paris Saint-Germain,2018-07-01,2018,2022,False,Not a loan,False,"ST, LW, RW",178.0,73.0,Right,91,ST,185500000,160000,203100000,408,78,91,73,83,83,394,92,79,63,70,90,458,96,96,92,92,82,404,86,77,86,76,79,341,62,38,91,80,70,84,100,34,34,32,42,13,5,7,11,6,2147,466,4,5,High,Low,3,96,86,78,91,39,76,1600
192448,Marc-André ter Stegen,Germany,28,90,93,FC Barcelona,2014-07-01,2014,2022,False,Not a loan,False,GK,187.0,85.0,Right,90,GK,110000000,260000,147700000,118,18,14,11,61,14,144,21,18,12,63,30,254,38,50,37,86,43,268,66,79,35,78,10,171,43,22,11,70,25,70,48,25,13,10,439,88,85,88,88,90,1442,484,4,1,Medium,Medium,3,88,85,88,90,45,88,130

In [65]:
#Saving cleaned dataset to new CSV file
df.to_csv('fifa21 raw data v2_cleaned.csv', index=False)